version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - API_URL=http://backend:8000
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8503:8503"
    environment:
      - API_URL=http://backend:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge